# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: qsy_test
  MYSQL_ROOT_PASSWORD: root

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - .cache/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  # Print out python version for debugging
  - python -V
  - pip install -U -r requirements.txt
  - cp .env.example .env

test:
  variables:
    DB_HOST: mysql:3306
    DB_USER: root
    DB_PASS: root
  script:
  - py.test tests